
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=levantos
      - POSTGRES_PASSWORD=password
      - PGDATA=postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  levantos-api:
    container_name: levantos-api
    image: levantosina/levantos-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
