name: CD - Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Adjust this path according to your project structure

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          # Login to Docker Hub
          echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          # Build Docker image
          docker build -t levantosina/levantos-api:${{ steps.build-number.outputs.BUILD_NUMBER }} .

          # Push Docker image to Docker Hub
          docker push levantosina/levantos-api:${{ steps.build-number.outputs.BUILD_NUMBER }}

      - name: Update Dockerrun.aws.json with new image tag
        run: |
          sed -i "s|levantosina/levantos-api:[^\\\"]*|levantosina/levantos-api:${{ steps.build-number.outputs.BUILD_NUMBER }}|" Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name:  ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.sha }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: backend/Dockerrun.aws.json

      - name: Commit and push Dockerrun.aws.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerrun.aws.json docker image with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push
